### ISSUE TITLE
notebook progress bar is not enabled

### ISSUE THREAD

**Issue by FlorinAndrei** [Slimmer-AI/mpire#20]
Jupyter Notebook on Windows. Code:

```
from mpire import WorkerPool
import time

def time_consuming_function(x, time=time):
    time.sleep(1)  # Simulate that this function takes long to complete
    return ...

from mpire import WorkerPool

with WorkerPool(n_jobs=5, use_dill=True) as pool:
    results = pool.map(time_consuming_function, range(100), progress_bar=True)
```

I do not see the `Widget Javascript not detected` error anywhere.

I've installed and enabled the widgets already.

```
pip install --user ipywidgets
jupyter nbextension enable --py --sys-prefix widgetsnbextension
```

**Comment by sybrenjansen** [comment]
Have you tried using ``tqdm`` without MPIRE to see if works? Have you tried restarting the notebook kernel after enabling widgets?

If it still doesn't work, then I would suggest you search for a solution on stackoverflow, as this issue is not related to MPIRE, but to ``tqdm`` not functioning in a Jupyter Notebook. E.g., have a look at https://stackoverflow.com/questions/57343134/jupyter-notebooks-not-displaying-progress-bars.

**Comment by FlorinAndrei** [comment]
tqdm definitely works. This displays a text-mode progress bar in the notebook:

```
from tqdm import tqdm
for _ in tqdm(range(10)):
    time.sleep(1)
```

This displays a GUI progress bar in the notebook:

```
from tqdm.notebook import tqdm
for _ in tqdm(range(10)):
    time.sleep(1)
```

**Important note:** The mpire code shown in my first comment actually does display a progress bar, but it's shown not in the notebook but in the terminal window where I run `jupyter notebook` to launch Jupyter.

The bug persists across numerous restarts of Jupyter and the whole system.

**Comment by sybrenjansen** [comment]
Will close the issue for now because there hasn't been any activity llately
