### ISSUE TITLE
pb with list as argument

### ISSUE THREAD

**Issue by ccaligaris** [Slimmer-AI/mpire#31]
Hello,

I meet with problem with a function using list of values as argument :

import time
def time_consuming_function(x):
    y=sum(x)
    time.sleep(1)  # Simulate that this function takes long to complete
    return y

when I use multiprocessing, it's OK :

with Pool(6) as pool :
    results = pool.map(time_consuming_function, [[0,1,2],[0,1,2]])
print(results)

# >>> [3,3]

when I use MPIRE, it doesn't work :

with WorkerPool(n_jobs=6) as pool:
    results = pool.map(time_consuming_function, [[0,1,2],[0,1,2]])

TypeError: 

Exception occurred in Worker-0 with the following arguments:
Arg 0: 0
Arg 1: 1
Arg 2: 2
TypeError: time_consuming_function() takes 1 positional argument but 3 were given

**Comment by sybrenjansen** [comment]
Hi @ccaligaris ,

This is because MPIRE treats these arguments slightly differently. When a task is an iterable, that iterable will be unpacked by default. This is also apparent from the error message, it says the function retrieves 3 arguments instead of 1. Have a look at https://slimmer-ai.github.io/mpire/usage/map/map.html#circumvent-argument-unpacking.

To fix your example, use the following:
```
with WorkerPool(n_jobs=6) as pool:
    results = pool.map(time_consuming_function, [([0,1,2],), ([0,1,2],)])
```
Or use:
```
from mpire.utils import make_single_arguments

with WorkerPool(n_jobs=6) as pool:
    results = pool.map(time_consuming_function, make_single_arguments([[0,1,2], [0,1,2]], generator=False))
```
