### ISSUE TITLE
Memory Overflow, how to force Use Virtual Memory?

### ISSUE THREAD

**Issue by xiasummer** [Slimmer-AI/mpire#65]
I encountered a problem with a very huge class object.

The calculation is not  hard, but if we use mpire to run multi-core process, the RAM of the computer is quickly ran out.

Surprisingly,  after the initialization, the ram usage quickly goes down to 50% of the computer when it's running.

Every time mpire is opening up a thread, it consumes a lot of RAM, but when it's running, the RAM quickly goes down.

So, if it's only when opening up a thread, can we use the huge virtual memory?
Or, can we initialize the threads one by one, not at the same time to avoid quickly using up all the Memory?

I'm using Windows 11.

**Comment by sybrenjansen** [comment]
The high RAM usage is purely from starting the process? So, even when you do absolutely nothing in the function your parallelizing, it still uses a lot of RAM? Then, because you're on Windows, that's probably due to the fact the object needs to be serialized x times (where x is the number of processes you use), send over the queue, and unserialized in the worker. In the process of unserializing, it basically reconstructs your object, which means an additional copy. Only after the object is recreated, it will throw away the serialized representation. In other words if you have 10 workers, then in total your object will be "copied" 20 times and after the workers are done reconstructing it you will be left with 10 copies. Hence the memory going up a lot and then going down again.

By using virtual memory, you're referring to using your disk as additional memory, right? I'm not sure how to do this in Python though. The other option of postponing spawning threads currently is not supported, but isn't hard to implement.

I see two options right now:
- As you're on Windows, you don't have the option to use fork and thus to use copy-on-write. This means copies are created of your very huge class object as mentioned earlier. Alternatively, you could save that object to disk and not load it in memory when starting your pool of workers. Then, inside a worker load the object again. If this still takes up too much memory because the loading of the object takes too much memory, you can consider using a Lock object to allow only one worker to load the object at a time.
- Implement worker start delay functionality. Either using some kind of synchronization primitive or delay in (milli)seconds.

Let me know if that first option will work for you, or if you really require the latter. Best of luck.
